In [93]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [130]:
data1=pd.read_csv("Financial_inclusion_dataset.csv")

In [131]:
data1.info()
data1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  object
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
dtypes: int64(3), object(10)
memory usage: 2.3+ MB

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [132]:
from ydata_profiling import ProfileReport

In [133]:
# Generate the profile report
profile = ProfileReport(data1, title=('Financial Inclusion Report'))

In [134]:
# Or generate an HTML report
profile.to_file("Financial Inclusion.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
100%|██████████| 13/13 [00:00<00:00, 116.03it/s]A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [96]:
data1['country'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

          Count  Pecentage
country
Rwanda     8735      37.13
Tanzania   6620      28.14
Kenya      6068      25.79
Uganda     2101       8.93

In [97]:
#Converting categorical to numerical so we can use knn
data1['country']=data1['country'].map({'Rwanda':0,'Tanzania':1,'Kenya':2, 'Uganda':3})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,2,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,2,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,2,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,2,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [98]:
data1['cellphone_access'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                  Count  Pecentage
cellphone_access
Yes               17454       74.2
No                 6070       25.8

In [99]:
#Converting categorical to numerical so we can use knn
data1['cellphone_access']=data1['cellphone_access'].map({'Yes':0,'No':1})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,Yes,Rural,0,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,2,2018,uniqueid_2,No,Rural,1,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,2,2018,uniqueid_3,Yes,Urban,0,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,2,2018,uniqueid_4,No,Rural,0,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,2,2018,uniqueid_5,No,Urban,1,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [100]:
data1['gender_of_respondent'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                      Count  Pecentage
gender_of_respondent
Female                13877      58.99
Male                   9647      41.01

In [101]:
#Converting categorical to numerical so we can use knn
data1['gender_of_respondent']=data1['gender_of_respondent'].map({'Female':0,'Male':1})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,Yes,Rural,0,3,24,0,Spouse,Married/Living together,Secondary education,Self employed
1,2,2018,uniqueid_2,No,Rural,1,5,70,0,Head of Household,Widowed,No formal education,Government Dependent
2,2,2018,uniqueid_3,Yes,Urban,0,5,26,1,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,2,2018,uniqueid_4,No,Rural,0,5,34,0,Head of Household,Married/Living together,Primary education,Formally employed Private
4,2,2018,uniqueid_5,No,Urban,1,8,26,1,Child,Single/Never Married,Primary education,Informally employed

In [102]:
data1['bank_account'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

              Count  Pecentage
bank_account
No            20212      85.92
Yes            3312      14.08

In [103]:
#Converting categorical to numerical so we can use knn
data1['bank_account']=data1['bank_account'].map({'Yes':0,'No':1})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,Rural,0,3,24,0,Spouse,Married/Living together,Secondary education,Self employed
1,2,2018,uniqueid_2,1,Rural,1,5,70,0,Head of Household,Widowed,No formal education,Government Dependent
2,2,2018,uniqueid_3,0,Urban,0,5,26,1,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,2,2018,uniqueid_4,1,Rural,0,5,34,0,Head of Household,Married/Living together,Primary education,Formally employed Private
4,2,2018,uniqueid_5,1,Urban,1,8,26,1,Child,Single/Never Married,Primary education,Informally employed

In [104]:
data1['marital_status'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                         Count  Pecentage
marital_status
Married/Living together  10749      45.69
Single/Never Married      7983      33.94
Widowed                   2708      11.51
Divorced/Seperated        2076       8.83
Dont know                    8       0.03

In [105]:
#Converting categorical to numerical so we can use knn
data1['marital_status']=data1['marital_status'].map({'Married/Living together':0,'Single/Never Married':1, 'Widowed':2, 'Divorced/Seperated':3, 'Dont know':4})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,Rural,0,3,24,0,Spouse,0,Secondary education,Self employed
1,2,2018,uniqueid_2,1,Rural,1,5,70,0,Head of Household,2,No formal education,Government Dependent
2,2,2018,uniqueid_3,0,Urban,0,5,26,1,Other relative,1,Vocational/Specialised training,Self employed
3,2,2018,uniqueid_4,1,Rural,0,5,34,0,Head of Household,0,Primary education,Formally employed Private
4,2,2018,uniqueid_5,1,Urban,1,8,26,1,Child,1,Primary education,Informally employed

In [106]:
data1['education_level'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                                 Count  Pecentage
education_level
Primary education                12791      54.37
No formal education               4515      19.19
Secondary education               4223      17.95
Tertiary education                1157       4.92
Vocational/Specialised training    803       3.41
Other/Dont know/RTA                 35       0.15

In [107]:
#Converting categorical to numerical so we can use knn
data1['education_level']=data1['education_level'].map({'Primary education':0,'No formal education':1, 'Secondary education':2, 'Tertiary education':3, 'Vocational/Specialised training':4, 'Other/Dont know/RTA':5})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,Rural,0,3,24,0,Spouse,0,2,Self employed
1,2,2018,uniqueid_2,1,Rural,1,5,70,0,Head of Household,2,1,Government Dependent
2,2,2018,uniqueid_3,0,Urban,0,5,26,1,Other relative,1,4,Self employed
3,2,2018,uniqueid_4,1,Rural,0,5,34,0,Head of Household,0,0,Formally employed Private
4,2,2018,uniqueid_5,1,Urban,1,8,26,1,Child,1,0,Informally employed

In [108]:
data1['job_type'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                              Count  Pecentage
job_type
Self employed                  6437      27.36
Informally employed            5597      23.79
Farming and Fishing            5441      23.13
Remittance Dependent           2527      10.74
Other Income                   1080       4.59
Formally employed Private      1055       4.48
No Income                       627       2.67
Formally employed Government    387       1.65
Government Dependent            247       1.05
Dont Know/Refuse to answer      126       0.54

In [109]:
#Converting categorical to numerical so we can use knn
data1['job_type']=data1['job_type'].map({'Self employed':0,'Government Dependent':1, 'Informally employed':2, 'Farming and Fishing':3, 'Remittance Dependent':4, 'No Income':5, 'Formally employed Government':6, 'Dont Know/Refuse to answer':7, 'Other Income':8, 'Formally employed Private':9,})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,Rural,0,3,24,0,Spouse,0,2,0
1,2,2018,uniqueid_2,1,Rural,1,5,70,0,Head of Household,2,1,1
2,2,2018,uniqueid_3,0,Urban,0,5,26,1,Other relative,1,4,0
3,2,2018,uniqueid_4,1,Rural,0,5,34,0,Head of Household,0,0,9
4,2,2018,uniqueid_5,1,Urban,1,8,26,1,Child,1,0,2

In [110]:
data1['location_type'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

               Count  Pecentage
location_type
Rural          14343      60.97
Urban           9181      39.03

In [111]:
#Converting categorical to numerical so we can use knn
data1['location_type']=data1['location_type'].map({'Rural':0,'Urban':1})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,0,0,3,24,0,Spouse,0,2,0
1,2,2018,uniqueid_2,1,0,1,5,70,0,Head of Household,2,1,1
2,2,2018,uniqueid_3,0,1,0,5,26,1,Other relative,1,4,0
3,2,2018,uniqueid_4,1,0,0,5,34,0,Head of Household,0,0,9
4,2,2018,uniqueid_5,1,1,1,8,26,1,Child,1,0,2

In [112]:
data1['relationship_with_head'].value_counts().to_frame('Count').assign(Pecentage=lambda x: (x['Count'] / x['Count'].sum()*100).round(2))

                        Count  Pecentage
relationship_with_head
Head of Household       12831      54.54
Spouse                   6520      27.72
Child                    2229       9.48
Parent                   1086       4.62
Other relative            668       2.84
Other non-relatives       190       0.81

In [113]:
#Converting categorical to numerical so we can use knn
data1['relationship_with_head']=data1['relationship_with_head'].map({'Head of Household':0,'Spouse':1, 'Child':2, 'Parent':3, 'Other relative':4, 'Other non-relatives':5})
data1.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,2,2018,uniqueid_1,0,0,0,3,24,0,1,0,2,0
1,2,2018,uniqueid_2,1,0,1,5,70,0,0,2,1,1
2,2,2018,uniqueid_3,0,1,0,5,26,1,4,1,4,0
3,2,2018,uniqueid_4,1,0,0,5,34,0,0,0,0,9
4,2,2018,uniqueid_5,1,1,1,8,26,1,2,1,0,2

In [114]:
#Choosing the features as x and the target as y
x=data1[['country','cellphone_access','location_type','relationship_with_head','gender_of_respondent', 'marital_status','education_level','job_type']]
y=data1['bank_account']

In [115]:
#split our data with test size of 20%
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [116]:
knn=KNeighborsClassifier(n_neighbors=1) #build our knn classifier

In [117]:
knn.fit(x_train,y_train) #Training KNN classifier

KNeighborsClassifier(n_neighbors=1)

In [118]:
y_pred = knn.predict(x_test)  #Testing
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [122]:
print('Acuuracy=',accuracy_score(y_pred,y_test))

Acuuracy= 0.8473963868225293

In [120]:
n_neighbors=30
scores=[]
for k in range(1,30):
    knn=KNeighborsClassifier(n_neighbors-k)
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    print('Accuracy for k=',k,'is:',round(accuracy_score(y_pred,y_test),2))
    scores.append(round(accuracy_score(y_pred,y_test),2))

Accuracy for k= 1 is: 0.89
Accuracy for k= 2 is: 0.88
Accuracy for k= 3 is: 0.88
Accuracy for k= 4 is: 0.88
Accuracy for k= 5 is: 0.88
Accuracy for k= 6 is: 0.88
Accuracy for k= 7 is: 0.88
Accuracy for k= 8 is: 0.88
Accuracy for k= 9 is: 0.88
Accuracy for k= 10 is: 0.88
Accuracy for k= 11 is: 0.88
Accuracy for k= 12 is: 0.88
Accuracy for k= 13 is: 0.88
Accuracy for k= 14 is: 0.88
Accuracy for k= 15 is: 0.88
Accuracy for k= 16 is: 0.88
Accuracy for k= 17 is: 0.88
Accuracy for k= 18 is: 0.87
Accuracy for k= 19 is: 0.88
Accuracy for k= 20 is: 0.88
Accuracy for k= 21 is: 0.88
Accuracy for k= 22 is: 0.87
Accuracy for k= 23 is: 0.88
Accuracy for k= 24 is: 0.87
Accuracy for k= 25 is: 0.88
Accuracy for k= 26 is: 0.86
Accuracy for k= 27 is: 0.87
Accuracy for k= 28 is: 0.78
Accuracy for k= 29 is: 0.85

# Test Log Regression

In [123]:
from sklearn.linear_model import LogisticRegression

In [124]:
#build our logistic model
logreg = LogisticRegression(max_iter=10000)

In [125]:
#fitting training data
logreg.fit(x_train, y_train)

LogisticRegression(max_iter=10000)

In [126]:
#testing model’s performance
y_pred  = logreg.predict(x_test)

In [127]:
print("Accuracy={:.2f}".format(logreg.score(x_test, y_test)))

Accuracy=0.88

In [128]:
print("Accuracy={:.2f}".format(logreg.score(x_test, y_pred)))

Accuracy=1.00

In [135]:
import joblib

# After fitting your model
joblib.dump(logreg, 'logistic_model.pkl')

['logistic_model.pkl']